#!/bin/sh

cd src

cd transformers-0.2.2.0
runhaskell Setup configure --user
runhaskell Setup build
runhaskell Setup install

cd ../mtl-2.0.1.0
runhaskell Setup configure --user
runhaskell Setup build
runhaskell Setup install

cd ../CC-delcont-0.2
runhaskell Setup configure --user
runhaskell Setup build
runhaskell Setup install

cd ../..
make ignorant-improved
